image: node:6.10.3

stages:

  - ver

  - init

  - tests

  - deploy

ver:

  stage: ver

  script:

    - node --version

    - whoami

init:

  stage: init

  script:


    - npm install
    - npm run build


deploy_staging:

  stage: deploy

  script:

    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/taxihub-frontend.git

    - git push heroku master

    - echo "Deployed to staging server"

  environment:

  name: staging

  url: https://taxihub-frontend.herokuapp.com/

  only:

    - master

deploy_production:

  stage: deploy

  script:

    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/taxihub-frontend.git

    - git push heroku master

    - echo "Deployed to production server"

  environment:

  name: production

  url: https://taxihub-frontend.herokuapp.com/

  when: manual

  only:

    - master