image: node:6.10.3

stages:

  - ver

  - init

  - tests

  - deploy

ver:

  stage: ver

  script:

    - node --version

    - whoami

init:

  stage: init

  script:

    - npm cache clean

    - rm -rf node-modules

    - npm install

run_tests:

  stage: tests

  script:

    - npm test

deploy_staging:

  stage: deploy

  script:

    - git remote add heroku https://heroku:$f078039f-7081-417c-8fc1-4d2fa7b4eedb@git.heroku.com/taxihub-stagingfront.git

    - git push heroku master

    - echo "Deployed to staging server"

  environment:

  name: staging

  url: https://taxihub-stagingfront.herokuapp.com/

  only:

    - master

deploy_production:

  stage: deploy

  script:

    - git remote add heroku https://heroku:$f078039f-7081-417c-8fc1-4d2fa7b4eedb@git.heroku.com/taxihub-prodfront.git

    - git push heroku master

    - echo "Deployed to production server"

  environment:

  name: production

  url: https://taxihub-prodfront.herokuapp.com/

  when: manual

  only:

    - master